//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public Adress()
        {
            this.CrimesHistory = new HashSet<CrimesHistory>();
            this.Criminal = new HashSet<Criminal>();
        }
    
        public int Id { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Number { get; set; }
        public string Complement { get; set; }
        public Nullable<int> IdCity { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<CrimesHistory> CrimesHistory { get; set; }
        public virtual ICollection<Criminal> Criminal { get; set; }
    }
}
