//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrimesHistory
    {
        public int Id { get; set; }
        public Nullable<int> IdCrimeType { get; set; }
        public Nullable<int> IdCrimeAdress { get; set; }
        public Nullable<System.Guid> IdCriminal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual CrimeTypes CrimeTypes { get; set; }
        public virtual Criminal Criminal { get; set; }
    }
}
