//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CriminalEntities : DbContext
    {
        public CriminalEntities()
            : base("name=CriminalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<CrimesHistory> CrimesHistory { get; set; }
        public virtual DbSet<CrimeTypes> CrimeTypes { get; set; }
        public virtual DbSet<Criminal> Criminal { get; set; }
        public virtual DbSet<SexType> SexType { get; set; }
        public virtual DbSet<State> State { get; set; }
    }
}
